### PR TITLE
fix: use Write key-value pair API when no metadata

### LINKED ISSUE #2: put does not work without metadata
`put` implementation does not work correctly.

https://github.com/markusahlstrand/cloudflare-kv-storage-rest/blob/e11e0e37d27b1b9acc08e09b0934216782061548/src/index.js#L128-L139

[Write key-value pair with metadata](https://api.cloudflare.com/#workers-kv-namespace-write-key-value-pair-with-metadata) always require `metadata` value.

I have received following response when `put("key", "value")` without metadata.

```json
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10047,
      "message": "multipart put request does not contain required form field 'metadata': '%!s(\u003cnil\u003e)'"
    }
  ],
  "messages": []
}
```

So, I think that the following conditional logic is required.

```js
  async put(key, value, options = {}) {
    const { expiration, expirationTtl, metadata } = options;

    const url = this.getUrlForKey(key);
    const searchParams = new URLSearchParams();

    if (expiration) {
      searchParams.append('expiration', expiration);
    } else if (expirationTtl) {
      searchParams.append('expiration_ttl', expirationTtl);
    }

    const headers = {
      'X-Auth-Email': this.authEmail,
      'X-Auth-Key': this.authKey,
    };

    url.search = searchParams.toString();

    if (!metadata) {
      // https://api.cloudflare.com/#workers-kv-namespace-write-key-value-pair
      // eslint-disable-next-line no-undef
      const response = await this.fetch(url.toString(), {
        method: "PUT",
        headers: { ...headers },
        body: value
      });
      return response.ok;
    } else {
      // https://api.cloudflare.com/#workers-kv-namespace-write-key-value-pair-with-metadata
      // eslint-disable-next-line no-undef
      const formData = new this.FormData();
      formData.append("value", value);
      formData.append("metadata", JSON.stringify(metadata));
      // eslint-disable-next-line no-undef
      const response = await this.fetch(url.toString(), {
        method: "PUT",
        headers: { ...formData.getHeaders(), ...headers },
        body: formData
      });
      return response.ok;
    }
  }
```

### PR DESCRIPTION
**Pull request by azu**
fix #2

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -124,18 +124,26 @@ module.exports = class KvStorage {
...
-      formData.append('metadata', JSON.stringify(metadata));
-    }
-
+    formData.append('metadata', JSON.stringify(metadata));
     // eslint-disable-next-line no-undef
     const response = await this.fetch(url.toString(), {
       method: 'PUT',
-      headers: { ...formData.headers, ...headers },
-      body: formData.stream,
+      headers: { ...formData.getHeaders(), ...headers },
```
Comment (azu) [inline src/index.js:145]: https://github.com/form-data/form-data use `formData.getHeaders()`

**Review by markusahlstrand — APPROVED** [review]
Think it looks good! Thanks for the contribution :)

**Comment by azu** [comment]
Thanks for merging!
